### ISSUE TITLE
Can u share PHEME dataset?

### ISSUE THREAD

**Issue by findmi** [Coder-HenryZa/RDMSC#2]

**Comment by findmi** [comment]
I want to reproducing your paper,thank u

**Comment by Coder-HenryZa** [comment]
Due to privacy protection, PHEME's user data cannot be shared publicly. Please leave your email address and I will send it to you later.

**Comment by findmi** [comment]
> Due to privacy protection, PHEME's user data cannot be shared publicly. Please leave your email address and I will send it to you later.

thank u very much ,plz send to rainmanv@163.com

**Comment by venmong** [comment]
> Due to privacy protection, PHEME's user data cannot be shared publicly. Please leave your email address and I will send it to you later.

Can u share PHEME dataset? my email is : 2254000350@qq.com
